version: "3"

services:
  nginx:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./content_home:/usr/share/nginx/html

  php:
    image: php:7-fpm
    volumes:
      - ./content_home:/usr/share/nginx/html
